### ISSUE TITLE
Easier validation of SSP completeness

### ISSUE THREAD

**Issue by rahearn** [GSA-TTS/docker-trestle#28]
## Story

As a devsecops engineer,
I would like to more easily fill in the oscal-optional, but ssp-required fields,
So that I can know what needs to be completed before I try to say I'm done

## Solution

```[tasklist]
### Tasks
- [ ] https://github.com/GSA-TTS/docker-trestle/issues/29
- [ ] https://github.com/GSA-TTS/docker-trestle/issues/31
```

## Acceptance Criteria

- [ ] The SSP can be filled in with the exact full structure that the LATO template expects to pull data from.

**Comment by rahearn** [comment]
Closing this tracker. The trestle enhancements piece can stand on its own
