### ISSUE TITLE
Enhancements to compliance-trestle to provide more jinja template helpers for formatting SSP data

### ISSUE THREAD

**Issue by rahearn** [GSA-TTS/docker-trestle#29]
```[tasklist]
### Tasks
- [x] Create POC for helpers to use in jinja ssp template
- [x] Open PR to upstream and collect feedback or other approaches
- [x] Implement helpers as Jinja extensions
- [x] Autoload extensions from plugins
- [x] Update plugins docs to mention jinja extensions behavior
- [ ] https://github.com/GSA-TTS/docker-trestle/issues/43
- [x] Update docker-trestle templates with new filters
- [ ] https://github.com/GSA-TTS/devtools-compliance/issues/32
```
