### ISSUE TITLE
Create a trestle plugin to validate gsa template-required fields and/or add the empty fields in the right spots

### ISSUE THREAD

**Issue by rahearn** [GSA-TTS/docker-trestle#31]
```[tasklist]
### Tasks
- [x] create `trestle gsa-validate` command
- [x] create `trestle gsa-defaults` command to fill in an existing SSP with default values for extra required fields
- [ ] https://github.com/GSA-TTS/docker-trestle/pull/35
```

**Comment by rahearn** [comment]
https://github.com/GSA-TTS/compliance-trestle-gsa
