### ISSUE TITLE
Use public pandoc images for pandoc commands, rather than installing in our image

### ISSUE THREAD

**Issue by rahearn** [GSA-TTS/docker-trestle#34]
## Story

As a devsecops engineer,
I would like to use a separate pandoc image,
So that I can use docker-trestle more easily since it is not so large

## Solution

```[tasklist]
### Tasks
- [x] use separate pandoc image (some more details here: https://gsa-tts.slack.com/archives/C04PZ8VB9V4/p1725847770192049?thread_ts=1724770684.871109&cid=C04PZ8VB9V4) (note: that's in a private channel that @rahearn can access)
```

## Acceptance Criteria

- [ ] docker-trestle image size greatly reduced
- [ ] can generate html version still
- [x] bonus: pdf generation works out of box
