### ISSUE TITLE
Add tag-ssp-revision script

### ISSUE THREAD

**Issue by rahearn** [GSA-TTS/docker-trestle#41]
## Story

As a ***devsecops engineer***,
I would like to ***have an easy way to add an entry to the revisions table***,
So that I can ***mark significant changes to the document and increase the sspp version number***

## Solution

```[tasklist]
### Tasks
- [ ] https://github.com/GSA-TTS/compliance-trestle-gsa/pull/6
- [ ] https://github.com/GSA-TTS/docker-trestle/pull/42
```

## Acceptance Criteria

- [x] script prepends a new revisions entry 
- [x] script can accept a UUID to mark as the author
- [x] script prompts for a summary of changes and saves under the revision.title field
- [x] script has defaults for last-modified and version, but can override each

**Comment by rahearn** [comment]
blocked until https://github.com/GSA-TTS/compliance-trestle-gsa/pull/6 merges
