### ISSUE TITLE
Update to compliance-trestle with jinja filters

### ISSUE THREAD

**Issue by rahearn** [GSA-TTS/docker-trestle#43]
## Story

As a ***docker-trestle maintainer***,
I would like to ***use a released version of trestle***,
So that I can ***stop maintaining my fork***

## Solution

```[tasklist]
### Tasks
- [x] See approach through to merge: https://github.com/oscal-compass/compliance-trestle/pull/1710
- [x] Update requirements.txt with released version 3.5.0
```

## Acceptance Criteria

- [x] docker-trestle back to using released version

**Comment by rahearn** [comment]
revisit once 1710 is merged and scheduled for release

**Comment by rahearn** [comment]
1710 not merged yet, but is now part of the 3.5.0 milestone

**Comment by rahearn** [comment]
3.5.0 should be released later today 🤞🏻
